# Generated by Django 3.2.18 on 2023-04-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=220)),
                ('budget', models.PositiveIntegerField()),
                ('employment', models.PositiveIntegerField()),
                ('joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
